version: '3'

services:
  pysample: 
    image: ${pysample}
    ports: # Port binding to host from docker container
      - "5000:5000" # Bind port 3000 of host to 3000 of container
    container_name: pysample
    restart: always # What to do if container crashes
    